version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false