// Code generated by MockGen. DO NOT EDIT.
// Source: delivery_repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/Avito-courses/course-go-avito-israpilovsha/internal/delivery/model"
	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeliveryRepository) Create(ctx context.Context, d *model.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeliveryRepositoryMockRecorder) Create(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeliveryRepository)(nil).Create), ctx, d)
}

// DeleteByOrderID mocks base method.
func (m *MockDeliveryRepository) DeleteByOrderID(ctx context.Context, orderID string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByOrderID indicates an expected call of DeleteByOrderID.
func (mr *MockDeliveryRepositoryMockRecorder) DeleteByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOrderID", reflect.TypeOf((*MockDeliveryRepository)(nil).DeleteByOrderID), ctx, orderID)
}

// GetByOrderID mocks base method.
func (m *MockDeliveryRepository) GetByOrderID(ctx context.Context, orderID string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockDeliveryRepositoryMockRecorder) GetByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockDeliveryRepository)(nil).GetByOrderID), ctx, orderID)
}

// WithTx mocks base method.
func (m *MockDeliveryRepository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockDeliveryRepositoryMockRecorder) WithTx(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockDeliveryRepository)(nil).WithTx), ctx, fn)
}
