// Code generated by MockGen. DO NOT EDIT.
// Source: courier_repository.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/Avito-courses/course-go-avito-israpilovsha/internal/courier/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourierRepository) Create(ctx context.Context, c *model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCourierRepositoryMockRecorder) Create(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourierRepository)(nil).Create), ctx, c)
}

// FindAvailable mocks base method.
func (m *MockCourierRepository) FindAvailable(ctx context.Context) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailable", ctx)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailable indicates an expected call of FindAvailable.
func (mr *MockCourierRepositoryMockRecorder) FindAvailable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailable", reflect.TypeOf((*MockCourierRepository)(nil).FindAvailable), ctx)
}

// GetAll mocks base method.
func (m *MockCourierRepository) GetAll(ctx context.Context) ([]*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCourierRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCourierRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockCourierRepository) GetByID(ctx context.Context, id int64) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCourierRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCourierRepository)(nil).GetByID), ctx, id)
}

// ReleaseExpired mocks base method.
func (m *MockCourierRepository) ReleaseExpired(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseExpired", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseExpired indicates an expected call of ReleaseExpired.
func (mr *MockCourierRepositoryMockRecorder) ReleaseExpired(ctx, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseExpired", reflect.TypeOf((*MockCourierRepository)(nil).ReleaseExpired), ctx, now)
}

// Update mocks base method.
func (m *MockCourierRepository) Update(ctx context.Context, c *model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourierRepositoryMockRecorder) Update(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourierRepository)(nil).Update), ctx, c)
}

// UpdateStatus mocks base method.
func (m *MockCourierRepository) UpdateStatus(ctx context.Context, id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCourierRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCourierRepository)(nil).UpdateStatus), ctx, id, status)
}
